name: Build and push lattice-ci-build

on:
  workflow_dispatch:

jobs:
  build-lattice-ci-build:
    name: Build and push Docker CI builds
    runs-on: ubuntu-latest
    steps:
      - name: Get dockerfile repo
        uses: actions/checkout@v2
      - name: Build and push image
        working-directory: ./lattice-ci-build
        run: |
          TAG=$(date -u +%Y%m%d%H%M%S)
          which docker
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build . --tag ghcr.io/${{github.repository}}/lattice-ci-build:$TAG
          docker push ghcr.io/${{github.repository}}/lattice-ci-build:$TAG
          docker tag ghcr.io/${{github.repository}}/lattice-ci-build:$TAG ghcr.io/${{github.repository}}/lattice-ci-build:latest
          docker push ghcr.io/${{github.repository}}/lattice-ci-build:latest
